### login super
POST {{url}}/user/login
Content-Type: application/json

{
  "username": "super",
  "password": "super",
  "tenant_id": 1
}

### login admin
POST {{url}}/user/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "tenant_id": 1
}

### login temp
POST {{url}}/user/login
Content-Type: application/json

{
  "username": "temp",
  "password": "temp",
  "tenant_id": 1
}