### login temp
POST {{url}}/login
Content-Type: application/json

{
  "username": "temp",
  "password": "temp"
}

### login stu1
POST {{url}}/login
Content-Type: application/json

{
  "username": "stu1",
  "password": "stu1"
}
