version: "3.9"
services:
  dorm:
    build:
      dockerfile: Dockerfile-dorm
    ports:
      - "9080:9080"
    extra_hosts:
      #- "host.docker.internal:host-gateway" # Windows and Mac
      - "host.docker.internal:172.17.0.1" # Linux
  order:
    build:
      dockerfile: Dockerfile-order
    ports:
      - "9081:9081"
    extra_hosts:
      #- "host.docker.internal:host-gateway" # Windows and Mac
      - "host.docker.internal:172.17.0.1" # Linux
  team:
    build:
      dockerfile: Dockerfile-team
    ports:
      - "9082:9082"
    extra_hosts:
      #- "host.docker.internal:host-gateway" # Windows and Mac
      - "host.docker.internal:172.17.0.1" # Linux
  token:
    build:
      dockerfile: Dockerfile-token
    ports:
      - "9083:9083"
    extra_hosts:
      #- "host.docker.internal:host-gateway" # Windows and Mac
      - "host.docker.internal:172.17.0.1" # Linux
  user:
    build:
      dockerfile: Dockerfile-user
    ports:
      - "9084:9084"
    extra_hosts:
      #- "host.docker.internal:host-gateway" # Windows and Mac
      - "host.docker.internal:172.17.0.1" # Linux
