version: "3.9"
services:
  dorm:
    build:
      dockerfile: Dockerfile-dorm
    ports:
      - "9080:9080"
  order:
    build:
      dockerfile: Dockerfile-order
    ports:
      - "9081:9081"
  team:
    build:
      dockerfile: Dockerfile-team
    ports:
      - "9082:9082"
  token:
    build:
      dockerfile: Dockerfile-token
    ports:
      - "9083:9083"
  user:
    build:
      dockerfile: Dockerfile-user
    ports:
      - "9084:9084"
  main:
    build:
      dockerfile: Dockerfile-main
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
