FROM golang:1.19

WORKDIR $GOPATH/src/github.com/zenpk/dorm-system

COPY . .

ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.cn

RUN go mod download

RUN make -C cmd/order build

EXPOSE 9081

ENTRYPOINT ["bin/order", "-mode", "prod"]
