Start-Process -FilePath "../../bin/dorm.exe"
Start-Process -FilePath "../../bin/order.exe"
Start-Process -FilePath "../../bin/team.exe"
Start-Process -FilePath "../../bin/token.exe"
Start-Process -FilePath "../../bin/user.exe"
