DROP DATABASE IF EXISTS `dorm`;
CREATE DATABASE `dorm`;

CREATE USER 'dorm'@'%' IDENTIFIED BY 'dorm';
REVOKE ALL PRIVILEGES ON *.* FROM 'dorm'@'%';
GRANT ALL PRIVILEGES ON `dorm`.* TO 'dorm'@'%';
FLUSH PRIVILEGES;
