DROP DATABASE IF EXISTS `dorm`;
CREATE DATABASE `dorm`;

CREATE USER 'admin'@'%' IDENTIFIED BY 'admin';
REVOKE ALL PRIVILEGES ON *.* FROM 'admin'@'%';
GRANT ALL PRIVILEGES ON `dorm`.* TO 'admin'@'%';
FLUSH PRIVILEGES;
