version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/db
      - ./scripts:/docker-entrypoint-initdb.d # initialize database from scripts/*.sql
    deploy:
      restart_policy:
        condition: on-failure
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - db:/data # https://hub.docker.com/_/redis/
      - ./redis.conf:/usr/local/etc/redis/redis.conf # initialize Redis from ./redis.conf
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  db:
