gin:
  mode: "debug"
zap:
  path: "logs/"
server:
  host: "0.0.0.0"
  port: 8080
  domain: "localhost"
cors:
  whitelist:
    - "localhost"
    - "127.0.0.1"
    - "."
mysql:
  host: "101.43.179.27"
  port: 3306
  username: "dorm"
  password: "dorm"
  database: "dorm"
redis:
  host: "101.43.179.27"
  port: 6379
  password: ""
  db: 0
jwt:
  secret: "demo_secret"
cookie:
  token_age: 31536000 # one year
time:
  format: "2006-01-02 15:04:05"
auth:
  password_length: 5 # minimal password length
