gin:
  mode: "release"
zap:
  path: "logs/"
server:
  host: "0.0.0.0"
  port: 8080
  domain: "host.docker.internal"
cors:
  whitelist:
    - "localhost"
    - "127.0.0.1"
    - "host.docker.internal"
mysql:
  host: "host.docker.internal"
  port: 3306
  username: "dorm"
  password: "dorm"
  database: "dorm"
  charset: "utf8mb4"
  parse_time: "true"
  loc: "UTC"
redis:
  host: "host.docker.internal"
  port: 6379
  password: "redis_pass"
  db: 0
etcd:
  endpoints:
    - "host.docker.internal:2379"
  dial_timeout: 3 # seconds
  scheme: "etcd"
jwt:
  secret: "my_secret"
  age_hour: 24 # 24 hours
refresh_token:
  age_hour: 720 # 30 days
cookie:
  access_token_age: 86400 # 1 day
  refresh_token_age: 2592000 # 1 month
datetime:
  format:
    date: "2006-01-02"
    time: "2006-01-02 15:04:05"
  timezone: 8 # GMT/UTC+8
  user_team_start_time: "2000-01-01 00:00:00"
  user_team_deadline: "2099-12-31 00:00:00"
  order_start_time: "2000-01-01 00:00:00"
  order_deadline: "2099-12-31 00:00:00"
auth:
  password_length: 4 # minimal password length
snowflake:
  node: 1
