server:
  host: "0.0.0.0"
  target: "127.0.0.1"
  port: 9081
etcd:
  target: "etcd://order"
  ttl: 3
kafka:
  brokers:
    - "101.43.179.27:19092"
  topic: "order"
timeout:
  rpc: 3
  submit: 8
mutex_prefix: "mutex_building:"
