zap:
  path: "logs/"
server:
  host: "0.0.0.0"
  port: 8080
  domain: "localhost"
cors:
  whitelist:
    - "localhost"
    - "127.0.0.1"
mysql:
  host: "localhost"
  port: 3306
  username: "dorm"
  password: "dorm"
  database: "dorm"
  charset: "utf8mb4"
  parse_time: "true"
  loc: "UTC"
redis:
  host: "localhost"
  port: 6379
  password: "redis_pass"
  db: 0
jwt:
  secret: "my_secret"
cookie:
  token_age: 31536000 # one year
time:
  format: "2006-01-02 15:04:05"
  zone: 8 # GMT/UTC+8
auth:
  password_length: 4 # minimal password length
snowflake:
  node: 1
