---
zap:
  log_path: "../../logs/testing.log" # unstable
server:
  host: "0.0.0.0"
  port: 80
  domain: "192.168.31.23"
cors:
  whitelist:
    - "localhost"
    - "127.0.0.1"
mysql:
  host: "localhost"
  port: 3306
  username: "dorm"
  password: "dorm"
  database: "dorm"
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
jwt:
  secret: "demo_secret"
cookie:
  token_age: 31536000 # one year
time:
  format: "2006-01-02 15:04:05"
auth:
  password_length: 5 # minimal password length
