// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: dorm.proto

package dorm

import (
	common "github.com/zenpk/dorm-system/internal/service/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildingInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num    string `protobuf:"bytes,1,opt,name=num,proto3" json:"num,omitempty"`
	Info   string `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	ImgUrl string `protobuf:"bytes,3,opt,name=imgUrl,proto3" json:"imgUrl,omitempty"`
}

func (x *BuildingInfo) Reset() {
	*x = BuildingInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dorm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuildingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildingInfo) ProtoMessage() {}

func (x *BuildingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dorm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildingInfo.ProtoReflect.Descriptor instead.
func (*BuildingInfo) Descriptor() ([]byte, []int) {
	return file_dorm_proto_rawDescGZIP(), []int{0}
}

func (x *BuildingInfo) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *BuildingInfo) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *BuildingInfo) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dorm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dorm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_dorm_proto_rawDescGZIP(), []int{1}
}

type MapReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err       *common.CommonResponse `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	RemainCnt map[string]string      `protobuf:"bytes,2,rep,name=remainCnt,proto3" json:"remainCnt,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MapReply) Reset() {
	*x = MapReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dorm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapReply) ProtoMessage() {}

func (x *MapReply) ProtoReflect() protoreflect.Message {
	mi := &file_dorm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapReply.ProtoReflect.Descriptor instead.
func (*MapReply) Descriptor() ([]byte, []int) {
	return file_dorm_proto_rawDescGZIP(), []int{2}
}

func (x *MapReply) GetErr() *common.CommonResponse {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *MapReply) GetRemainCnt() map[string]string {
	if x != nil {
		return x.RemainCnt
	}
	return nil
}

type GetAllReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err   *common.CommonResponse `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Infos []*BuildingInfo        `protobuf:"bytes,2,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *GetAllReply) Reset() {
	*x = GetAllReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dorm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllReply) ProtoMessage() {}

func (x *GetAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_dorm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllReply.ProtoReflect.Descriptor instead.
func (*GetAllReply) Descriptor() ([]byte, []int) {
	return file_dorm_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllReply) GetErr() *common.CommonResponse {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *GetAllReply) GetInfos() []*BuildingInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

var File_dorm_proto protoreflect.FileDescriptor

var file_dorm_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x6f,
	0x72, 0x6d, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x4c, 0x0a, 0x0c, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e,
	0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x67, 0x55, 0x72, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x22, 0x0e,
	0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xaf,
	0x01, 0x0a, 0x08, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x03, 0x65,
	0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x3b, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x43,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64, 0x6f, 0x72, 0x6d, 0x2e,
	0x4d, 0x61, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x43,
	0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x43,
	0x6e, 0x74, 0x1a, 0x3c, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x43, 0x6e, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x61, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x28, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x28, 0x0a, 0x05, 0x69, 0x6e, 0x66,
	0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x6f, 0x72, 0x6d, 0x2e,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x6e,
	0x66, 0x6f, 0x73, 0x32, 0x6f, 0x0a, 0x04, 0x44, 0x6f, 0x72, 0x6d, 0x12, 0x34, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x43, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x64, 0x6f,
	0x72, 0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0e, 0x2e, 0x64, 0x6f, 0x72, 0x6d, 0x2e, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x31, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x12, 0x2e, 0x64, 0x6f,
	0x72, 0x6d, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x11, 0x2e, 0x64, 0x6f, 0x72, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x7a, 0x65, 0x6e, 0x70, 0x6b, 0x2f, 0x64, 0x6f, 0x72, 0x6d, 0x2d, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x64, 0x6f, 0x72, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_dorm_proto_rawDescOnce sync.Once
	file_dorm_proto_rawDescData = file_dorm_proto_rawDesc
)

func file_dorm_proto_rawDescGZIP() []byte {
	file_dorm_proto_rawDescOnce.Do(func() {
		file_dorm_proto_rawDescData = protoimpl.X.CompressGZIP(file_dorm_proto_rawDescData)
	})
	return file_dorm_proto_rawDescData
}

var file_dorm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dorm_proto_goTypes = []interface{}{
	(*BuildingInfo)(nil),          // 0: dorm.BuildingInfo
	(*EmptyRequest)(nil),          // 1: dorm.EmptyRequest
	(*MapReply)(nil),              // 2: dorm.MapReply
	(*GetAllReply)(nil),           // 3: dorm.GetAllReply
	nil,                           // 4: dorm.MapReply.RemainCntEntry
	(*common.CommonResponse)(nil), // 5: common.CommonResponse
}
var file_dorm_proto_depIdxs = []int32{
	5, // 0: dorm.MapReply.err:type_name -> common.CommonResponse
	4, // 1: dorm.MapReply.remainCnt:type_name -> dorm.MapReply.RemainCntEntry
	5, // 2: dorm.GetAllReply.err:type_name -> common.CommonResponse
	0, // 3: dorm.GetAllReply.infos:type_name -> dorm.BuildingInfo
	1, // 4: dorm.Dorm.GetRemainCnt:input_type -> dorm.EmptyRequest
	1, // 5: dorm.Dorm.GetAll:input_type -> dorm.EmptyRequest
	2, // 6: dorm.Dorm.GetRemainCnt:output_type -> dorm.MapReply
	3, // 7: dorm.Dorm.GetAll:output_type -> dorm.GetAllReply
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dorm_proto_init() }
func file_dorm_proto_init() {
	if File_dorm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dorm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuildingInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dorm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dorm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dorm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dorm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dorm_proto_goTypes,
		DependencyIndexes: file_dorm_proto_depIdxs,
		MessageInfos:      file_dorm_proto_msgTypes,
	}.Build()
	File_dorm_proto = out.File
	file_dorm_proto_rawDesc = nil
	file_dorm_proto_goTypes = nil
	file_dorm_proto_depIdxs = nil
}
