grpc:
	protoc common.proto --proto_path=../../internal/api \
	--go_out=../../internal/service/common --go_opt=paths=source_relative \
	--go-grpc_out=../../internal/service/common --go-grpc_opt=paths=source_relative
